export const JOBS = [
  {
    id: 1,
    title: "Senior ML Engineer",
    company: "Arbisoft",
    location: "Lahore, PK · Remote",
    salary: "PKR 4–6L/mo",
    tags: ["Python", "PyTorch", "LLMs"],
    match: 94,
    deadline: "3 days left",
    color: "#0f2a1e",
    accent: "#1d9e75",
    logo: "ML",
  },
  {
    id: 2,
    title: "Full-Stack Developer",
    company: "Systems Ltd",
    location: "Karachi, PK",
    salary: "PKR 2.5–3.5L/mo",
    tags: ["React", "Django", "PostgreSQL"],
    match: 89,
    deadline: "5 days left",
    color: "#0c1f3a",
    accent: "#378add",
    logo: "FS",
  },
  {
    id: 3,
    title: "Cloud Solutions Architect",
    company: "10Pearls",
    location: "Islamabad, PK · Hybrid",
    salary: "PKR 5–8L/mo",
    tags: ["Azure", "Docker", "Terraform"],
    match: 81,
    deadline: "1 week left",
    color: "#1f0e2e",
    accent: "#7f77dd",
    logo: "CA",
  },
  {
    id: 4,
    title: "DevOps Engineer",
    company: "Contour Software",
    location: "Karachi, PK",
    salary: "PKR 3–5L/mo",
    tags: ["Kubernetes", "CI/CD", "AWS"],
    match: 76,
    deadline: "2 weeks left",
    color: "#1f1200",
    accent: "#ef9f27",
    logo: "DO",
  },
];

export const BENTO_CARDS = [
  {
    id: "ai",
    span: "lg:col-span-2 lg:row-span-2",
    tag: "AI-Powered Matching",
    headline: "Your CV, understood by AI",
    body: "Upload once. Our RAG pipeline extracts every skill, project, and achievement — then matches you to roles with surgical precision.",
    icon: "✦",
    bgColor: "#0f0f0f",
    accent: "#1d9e75",
    large: true,
  },
  {
    id: "gap",
    span: "",
    tag: "Skill Gap",
    headline: "Know exactly what you're missing",
    body: "Per-job breakdown of the exact skills each role demands.",
    icon: "◈",
    bgColor: "#0a1628",
    accent: "#378add",
    large: false,
  },
  {
    id: "ats",
    span: "",
    tag: "ATS Score",
    headline: "Beat every filter",
    body: "Real-time ATS compatibility scoring before you apply.",
    icon: "◎",
    bgColor: "#1a0f28",
    accent: "#7f77dd",
    large: false,
  },
  {
    id: "track",
    span: "",
    tag: "Application Tracker",
    headline: "One dashboard, all apps",
    body: "Track status from applied → interview → hired.",
    icon: "⬡",
    bgColor: "#1a1000",
    accent: "#ef9f27",
    large: false,
  },
  {
    id: "alert",
    span: "",
    tag: "Deadline Alerts",
    headline: "Never miss a closing",
    body: "Smart notifications before deadlines hit.",
    icon: "⌖",
    bgColor: "#1a0808",
    accent: "#e24b4a",
    large: false,
  },
  {
    id: "cv",
    span: "lg:col-span-2",
    tag: "CV Builder",
    headline: "From raw info to interview-ready in minutes",
    body: "AI-guided CV maker tailors your résumé to each job. Export as PDF. One click.",
    icon: "▣",
    bgColor: "#0f0f0f",
    accent: "#1d9e75",
    large: false,
  },
];

export const TEAM = [
  {
    name: "Salman Khan",
    role: "Backend + ML",
    enroll: "02-131232-121",
    lead: true,
    initials: "SK",
    color: "#1d9e75",
  },
  {
    name: "Zohaib Arshad Noor",
    role: "Skill Gap + Testing",
    enroll: "02-131232-066",
    lead: false,
    initials: "ZA",
    color: "#378add",
  },
  {
    name: "Keyan Majid",
    role: "Frontend + CV Maker",
    enroll: "02-131232-021",
    lead: false,
    initials: "KM",
    color: "#7f77dd",
  },
  {
    name: "Jawad Ul Hassan",
    role: "Jobs + ATS",
    enroll: "02-131232-069",
    lead: false,
    initials: "JH",
    color: "#ef9f27",
  },
];

export const TECH_STACK = [
  "Django · DRF",
  "React · Vite · Tailwind",
  "Azure · PostgreSQL",
  "ChromaDB · RAG",
  "Claude API (Anthropic)",
  "Redis · Celery",
];

export const NAV_LINKS = [
  { label: "Features", href: "#features" },
  { label: "Jobs", href: "#jobs" },
  { label: "How it Works", href: "#how" },
  { label: "Team", href: "#team" },
];

export const ACCENT = "#1d9e75";
